name: Bug Report
description: Report a bug, or an issue with out felstorm server.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form! Please make sure to fill all fields, including the Title above.
  - type: dropdown
    id: Type Bug
    attributes:
      label: Type bug
      options:
        - "Achievements"
        - "Battle Pets"
        - "Class Halls"
        - "Classes - Death Knight"
        - "Classes - Demon Hunter"
        - "Classes - Druid"
        - "Classes - Hunter"
        - "Classes - Mage"
        - "Classes - Monk"
        - "Classes - Paladin"
        - "Classes - Priest"
        - "Classes - Rogue"
        - "Classes - Shaman"
        - "Classes - Warlock"
        - "Classes - Warrior"
        - "Garrison"
        - "General"
        - "Instances"
        - "Other bugs"
        - "Other quests"
        - "Professions"
        - "PVP"
        - "Quests -  Eastern Kingdom"
        - "Quests - Argus"
        - "Quests - Broken Isles"
        - "Quests - Cataclysm"
        - "Quests - Draenor"
        - "Quests - Northrend"
        - "Quests - Outland"
        - "Quests - Pandaria"
        - "Quests - Kalimdor"
        - "Quest Worldquest"
        - "World events"
        - "Item - Classic"
        - "Item - TBC"
        - "Item - Wotlk"
        - "Item - Cataclysm"
        - "Item - Mists of Pandaria"
        - "Item - Warlords of Draenor"
        - "Item - Legion"
        - "Misc - Translation"
      validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the bug or the issue here in detail, what is happening, and why u think its broken.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: |
        Tell us what should happen instead, if possible include youtube links to the quest, boss, object, item etc.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: |
        1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead or for 3.3.5a branch at https://aowow.trinitycore.info/ page.  
        2. Step 2
        3. Step 3
    validations:
      required: true
  - type: dropdown
    id: Faction
    attributes:
      label: Faction
      options:
        - Horde
        - Alliance
    validations:
      required: true
  - type: textarea
    id: Level, Class, and Spec
    attributes:
      label: Level, Class, and Spec
      description: |
        110, warlock, Demonology For example.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: |
        Operating System, i.e. Windows 10 x64, Debian 10 x64, etc
    validations:
      required: true
  - type: textarea
    id: Notes
    attributes:
      label: Additional Notes
      description: |
        Any other information u believe could be valueable in this bug report.
    validations:
      required: true
